%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/E/Documents/Advisers/Rust/Simulations/geometric
%    resetting/Phong_et_al_2013_data_25_100.xlsx Worksheet: 100
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/09/26 03:46:47

function data = loadConnieData(SHEETNAME)
%% Import the data
[~, ~, raw] = xlsread('./Phong_et_al_2013_data_25_100.xlsx',SHEETNAME);
raw = raw(2:end,:);

%% Create output variable
data1 = reshape([raw{:}],size(raw));

%% Create dataset array
data = dataset;

%% Allocate imported array to column variable names
data.S = data1(:,1);
data.T = data1(:,2);

%% Clear temporary variables
clearvars data1 raw;

end