%2017-03-29, EL: plot results of bootstrapped simulations to generate Fig.
%4-figSup2(C)
%
% This script processes simulation results generated by
% runPhOsc_Boot_LinNLin.m. Input those into the 
% SIM_BOOT_NONLIN = ['FILENAME'] and SIM_BOOT_LIN = ['FILENAME'] fields.
% below.
%
% dependencies: export_fig.m from FileExchange for figure export.

clear all;
close all;
clc;
cd(['.']);
%% input parameters
toexp_VitroSilico = 0; %export figs?
TOSAVE_DATA = 0;
TOLOAD_OLD_SIMULATION_ONE = 1; %load data from first simulation? (1=yes)
TOLOAD_OLD_SIMULATION_TWO = 1; %load data from second simulation? (1=yes)

%files containing simulation results
SIM_BOOT_NONLIN = ['saved_data/2017-03-29_NonLin_1000.mat']; %for simulations based on non-linear L and D
SIM_BOOT_LIN    = ['saved_data/2017-03-29_Lin_1000.mat']; %for simulations based on linearized L and D

%% load results of first simulation here
if TOLOAD_OLD_SIMULATION_ONE == 1
    SIMULATION_BOOT = load(SIM_BOOT_NONLIN);
    SIM = SIMULATION_BOOT.VAR;
    dawnphase = SIM.dawnphase;
    duskphase = SIM.duskphase;
    duskphaseshift = SIM.duskphaseshift;
    dawnphaseshift = SIM.dawnphaseshift;
    peakT = SIM.peakT;
    TDRIVE=SIM.TDRIVE; %24.0;
    TEND = SIM.TEND; %250;
    boot = SIM.boot;
    startphase = SIM.startphase;
    dutyfrac=SIM.dutyfrac; %[4:0.25:18]/24;
    numcyc = SIM.numcyc; %1:10;
    
end

%% saved data from in vitro entrainment expt (Fig. 2C)
vitro.pkT = [5.9400    7.6022    8.4327    9.5088   10.3786   12.1922];
vitro.pkT_Err = [0.3521    0.4818    0.3149    0.3112    0.2825    0.3598];
vitro.pp = [6     8    10    12    14    18];

%% collect variables for plotting
plotphase = dawnphase+dawnphaseshift;
plotphase = mod(plotphase,1);
plotphase(plotphase > 0.5) = plotphase(plotphase > 0.5) - 1;

%% select only those tau's where entrained stably
STDEV_LIM = 0.01;

NUMENTR=4; %for nonlinear case
for b=boot
    for df=1:numel(dutyfrac)
        plotphase_stdev(df,b) = std(squeeze(plotphase(df,(end-NUMENTR):end,b)));
        [~,plotphase_stdev(df,b),~] = ...
            circleMean(squeeze(plotphase(df,(end-NUMENTR):end,b)),1,[]);
        if plotphase_stdev(df,b) > STDEV_LIM
            entrained(df,b) = 0;
        else
            entrained(df,b) = 1;
        end
    end
end

%display some entrainment stats
disp(['Total no. sims.: ' num2str(numel(entrained))]);
disp(['No. entrained sims.: ' num2str(sum(sum(entrained)))]);
disp(['Frac entrained: ' num2str(...
    sum(sum(entrained))/...
    numel(entrained)...
    )]);

%specifically for tau between 8 and 16
gf = dutyfrac <= 16/24 & dutyfrac >= 8/24;
disp(['Total no. sims. tau=6-18: ' num2str(numel(entrained(gf,:)))]);
disp(['No. entrained sims. tau=6-18: ' num2str(sum(sum(entrained(gf,:))))]);
disp(['Frac entrained tau=6-18: ' num2str(...
    sum(sum(entrained(gf,:)))/...
    numel(entrained(gf,:))...
    )]);

%% figure out how quickly you entrain
pstdev=[];
numToEnt=[];
NME=3;

for b=boot
    for df=1:numel(dutyfrac)
        for n=1:numel(numcyc)-NME
            %pstdev(df,b,n) = std(squeeze(plotphase(df,n:n+NME,b)));
            [~,pstdev(df,b,n),~] = ...
                circleMean(squeeze(plotphase(df,n:n+NME,b)),1,[]);
        end
        
        %find index of
        nte = find(pstdev(df,b,:) <= STDEV_LIM,1,'first');
        if ~isempty(nte)
            numToEnt(b,df) = numcyc(nte);
        else
            numToEnt(b,df) = nan;
        end
    end
end

%% find all those entrained within 3 cycles
%and how many unentrained for daylengths 6-18 hrs
gf = dutyfrac <= 18/24 & dutyfrac >= 6/24;
gNumToEnt = numToEnt(:,gf);

num1to3 = sum(sum(gNumToEnt == 1 | gNumToEnt == 2 | gNumToEnt == 3));
numNan = sum(sum(isnan(gNumToEnt)));
numNet = numel(gNumToEnt);
fracQuick = num1to3/numNet;
fracQuick_notNan = num1to3/(numNet-numNan);
disp([num2str(fracQuick) ' entrained within 3 cycles']);
disp([num2str(fracQuick_notNan) ' entrained within 3 cycles out of successful simulations']);

%% plot avg phase+/-std for entrained tau's for entire boostrapped set
%go through dfs, collect [tau, taustd]
for df=1:numel(dutyfrac)
    tau(df) = dutyfrac(df);
    entr = logical(entrained(df,:));
    goodph = plotphase(df,end,entr);
    %goodph = goodph(goodph < 0.33);
    [taumean(df), taustd(df), taubreakpt(df)] = circleMean(goodph, 1, []);
end

%filter out phases where none entrained
baddf = isnan(taumean);
tau=tau(~baddf);
taumean = taumean(~baddf);
taustd=taustd(~baddf);
taubreakpt=taubreakpt(~baddf);

z=1/(2*pi);
%inputs to fvec must be in [0,1] phase units
fvec = (@(x) (0.5-x)/(1/24)); %convert phase units to CT

%add pts for filled area polygon for std deviations
yHi = taumean + taustd;
yLo = taumean - taustd;
yHi2 = taumean + 2*taustd;
yLo2 = taumean - 2*taustd;

%% plot 
fErrorBar = figure();
blueCol = cold(100);
lightBlue = [217 229 240]/255;
darkBlue = [191 209 229]/255;
pFill2 = fill(24*[tau fliplr(tau)],fvec([yHi2 fliplr(yLo2)]),...
    lightBlue,...
    'linestyle','none');
hold on;
pFill = fill(24*[tau fliplr(tau)],...
    fvec([yHi fliplr(yLo)]), darkBlue,...
    'linestyle','none','facealpha',0.5);
hold on;
pVitro=errorbar(vitro.pp,vitro.pkT,vitro.pkT_Err,'bs',...
    'markersize',4,'markerfacecolor','b',...
    'markeredgecolor','none','linestyle','none');
hold on;
legend([pVitro,pFill, pFill2],...
    'in vitro','simulation \pm \sigma','simulation \pm 2\sigma',...
    'location','northwest');
legend boxoff;
xlabel('day length \tau (hours)');
ylabel('peak time t_{pk} (hours after dawn)');
set(gca,'xlim',[0 24],'ylim',sort(fvec([-0.5 0.5])),...
    'xtick',0:6:24,'ytick',sort(fvec([-0.5:(1/4):0.5])));
grid off;
set(fErrorBar,'units','inches','position',[0 0 4 3]);
%%
if toexp_VitroSilico == 1
    export_fig([pwd '/' getDate('yyyy-mm-dd') '_fInVitroSilico_'...
        'NonParamBoot' num2str(max(boot)) '_ErrorBar_' ...
        getDate('HH.MM.DD')],...
        '-cmyk','-painters','-pdf',fErrorBar);
end

%% proceed only if have a second simulation set to load (e.g., linearized step funs)
if TOLOAD_OLD_SIMULATION_TWO == 1
    SIMULATION_BOOT = load(SIM_BOOT_LIN);
    SIM = SIMULATION_BOOT.VAR;
    dawnphase = SIM.dawnphase;
    duskphase = SIM.duskphase;
    duskphaseshift = SIM.duskphaseshift;
    dawnphaseshift = SIM.dawnphaseshift;
    peakT = SIM.peakT;
    TDRIVE=SIM.TDRIVE; %24.0;
    TEND = SIM.TEND; %250;
    boot = SIM.boot;
    startphase = SIM.startphase;
    dutyfrac=SIM.dutyfrac; %[4:0.25:18]/24;
    numcyc = SIM.numcyc; %1:10;
    
    %% collect variables for plotting
    plotphase = dawnphase+dawnphaseshift;
    plotphase = mod(plotphase,1);
    plotphase(plotphase > 0.5) = plotphase(plotphase > 0.5) - 1;
    
    %% select only those tau's where entrained stably
    STDEV_LIM = 0.01;
    
    NUMENTR=4; %for linear case
    for b=boot
        for df=1:numel(dutyfrac)
            plotphase_stdev(df,b) = std(squeeze(plotphase(df,(end-NUMENTR):end,b)));
            [~,plotphase_stdev(df,b),~] = ...
                circleMean(squeeze(plotphase(df,(end-NUMENTR):end,b)),1,[]);
            if plotphase_stdev(df,b) > STDEV_LIM
                entrained(df,b) = 0;
            else
                entrained(df,b) = 1;
            end
        end
    end
    
    %display some entrainment stats
    disp(['Total no. linear sims.: ' num2str(numel(entrained))]);
    disp(['No. entrained linear sims.: ' num2str(sum(sum(entrained)))]);
    disp(['Frac entrained linear: ' num2str(...
        sum(sum(entrained))/...
        numel(entrained)...
        )]);
    
    %specifically for tau between 8 and 16
    gf = dutyfrac <= 16/24 & dutyfrac >= 8/24;
    disp(['Total no. linear sims. tau=6-18: ' num2str(numel(entrained(gf,:)))]);
    disp(['No. entrained linear sims. tau=6-18: ' num2str(sum(sum(entrained(gf,:))))]);
    disp(['Frac entrained linear tau=6-18: ' num2str(...
        sum(sum(entrained(gf,:)))/...
        numel(entrained(gf,:))...
        )]);
    
    
    %% plot avg phase+/-std for entrained tau's for second dataset
    %go through dfs, collect [tau, taustd]
    for df=1:numel(dutyfrac)
        tau(df) = dutyfrac(df);
        entr = logical(entrained(df,:));
        goodph = plotphase(df,end,entr);
        goodph = goodph(goodph < 0.33);
        %     taumean(df) = nanmean(goodph);
        %     taustd(df) = nanstd(goodph);
        [taumean(df), taustd(df), taubreakpt(df)] = circleMean(goodph, 1, []);
    end
    %filter out phases where none entrained
    baddf = isnan(taumean);
    tau=tau(~baddf);
    taumean = taumean(~baddf);
    taustd=taustd(~baddf);
    taubreakpt=taubreakpt(~baddf);
    
    %go back to old figure
    figure(fErrorBar);
    %pErr2 = errorbar(24*dutyfrac,taumean,taustd,'gs-','linewidth',2);
    greenCol = [96 192 96]/255;
    pErr3=fill(24*[tau fliplr(tau)],...
        fvec([taumean+taustd fliplr(taumean-taustd)]), ...
        greenCol, 'linestyle','none','facealpha',0.5);
    
    %get rid of 2sigma on nonparam
    delete(pFill2);
    
    legend([pVitro,pFill,pErr3],...%, pFill2],...
        'in vitro \pm \sigma','simulation \pm \sigma','linearized simulation \pm \sigma',...
        'location','southwest');
    uistack(pVitro,'top');
    legend boxoff;
    %%
    if toexp_VitroSilico == 1
        export_fig([pwd '/' getDate('yyyy-mm-dd') '_fInVitroSilicoAndLin_'...
            'NonParamBoot' num2str(max(boot)) '_ErrorBar_' ...
            getDate()],...
            '-cmyk','-painters','-pdf',fErrorBar);
    end
       
end
