%2017-06-26, EL: modified to generat Fig. 4-figSup1(B) and Fig.
%4-figSup2(B).
%2017-03-29, EL: generate Figure 4-figSup1(B), Figure 4-figSup4(B)
%plot a single entrainment simulation using linear or nonlinear step functions
%
% This script loads results of simulations generated by
% runPhOsc_Boot_LinNLin_inKaiCPhaseUnits.m.
% These should be marked in the variables NONLIN_BOOT = [FILENAME] and LIN_BOOT =
% [FILENAME].
%
% This script also relies on step functions in the variable
% STEPFUN_BOOT=[FILENAME]. 
%
% dependencies: export_fig.m from FileExchange to export figures.

clear all;
close all;
clc;
INDIR=['.'];
cd(INDIR);

%% pick which step functions you used in your simulations 
% STEPFUN_BOOT = ['../helper functions and shared files/'...
%     '2017-03-17_stepFun_inKaiCPhase_19.20.23.mat'];
STEPFUN_BOOT = ['../helper functions and shared files/'...
    '2017-06-05_widefit_mergedStepFuns_11.30.54.mat'];

%% pick which datasets you want to analyze
%datasets generated from bootstrapped simulations based on...
%... nonlinear L and D funs (
NONLIN_BOOT = ['saved_data/2017-06-05_11.53.10_NonLin_FAST_4.mat']; 
%... linearized versions of the same L and D funs
LIN_BOOT = ['saved_data/2017-06-05_11.53.11_Lin_FAST_4.mat'];

%use linear or nonlinear step funs?
TOPLOT_LIN_NONLIN = 1; %[0=use nonlin step funs sims, 1=use linearized] 

boot = [2]; %which simulations to do you want to run?
LO_PP = 4; %which range of photoperiods from the simulations to plot (in hours)
HI_PP = 18;
TOEXP_DOUBLEFIG = 1; %save fig?
TODISP = 1;

%% load in vitro data from entrainment expt. (Fig. 2-figSup2)
load(['../helper functions and shared files/'...
    '2017-03-17_inVitroPP_fits_eachExpOwnPer_03.53.51.mat']); 
%add (7/6)*pi to make step fun data to correspond to KaiC phosphorylation phases
vitro.dawnPhase = vitro.dawnPhase + (7*pi/6); 

%% load step functions
%NOTE! must be in radians. don't normalize by 2*pi
load([INDIR '/' STEPFUN_BOOT]);

%% load simulation data from saved files
if TOPLOT_LIN_NONLIN == 0
    SIMULATION_BOOT = NONLIN_BOOT;
elseif TOPLOT_LIN_NONLIN == 1
    SIMULATION_BOOT = LIN_BOOT;
end
SIMULATION_BOOT = load(SIMULATION_BOOT);
SIM = SIMULATION_BOOT.VAR;
dawnphase = SIM.dawnphase;
duskphase = SIM.duskphase;
duskphaseshift = SIM.duskphaseshift;
dawnphaseshift = SIM.dawnphaseshift;
peakT = SIM.peakT;
TDRIVE=SIM.TDRIVE; %24.0;
dutyfrac=SIM.dutyfrac; %[4:1:18]/24;
numcyc = SIM.numcyc; %1:20;
TEND = SIM.TEND; %max(numcyc)*TDRIVE;

%% collect variables for plotting
plotphase = dawnphase+dawnphaseshift;
plotphase = mod(plotphase,1);
plotphase(plotphase > 0.3) = plotphase(plotphase > 0.3) - 1;

%% select only those taus where entrained stably
for b=boot
    NUMENTR=4;
    for df=1:numel(dutyfrac)
        plotphase_stdev(df,b) = std(squeeze(plotphase(df,(end-NUMENTR):end,b)));
        if plotphase_stdev(df,b) > 0.1
            entrained(df,b) = 0;
        else
            entrained(df,b) = 1;
        end
    end
end

%% set up colors just for pts in linear region
colorInd = dutyfrac >= LO_PP/24 & dutyfrac <= HI_PP/24;
numcolors = sum(colorInd);
colors = zeros(numel(dutyfrac),3);
colors(colorInd,:) = hot(numcolors);
colormap(colors);

%% plot entrained phase in silico vs in vitro
fInVitroSilico=figure();
colormap(colors);

%% plot bootstrapped step functions
for b=boot
    if sum(entrained(:,b) > 0)
        TLIGHT=T_hiATP_mix(b);
        TDARK=T_loATP_mix(b);
        STEPUP.phase = up_mix{b}.phase;
        STEPUP.phaseShift = up_mix{b}.phaseShift;
        STEPDOWN.phase = down_mix{b}.phase;
        STEPDOWN.phaseShift = down_mix{b}.phaseShift;
        
        %linearized versions
        STEPUP.linPhase = up_mix{b}.linPhase;
        STEPUP.linPhaseShift = up_mix{b}.linPhaseShift;
        STEPUP.linFit = up_mix{b}.linFit;
        STEPDOWN.linPhase = down_mix{b}.linPhase;
        STEPDOWN.linPhaseShift = down_mix{b}.linPhaseShift;       
        STEPDOWN.linFit = down_mix{b}.linFit;
        
        z=(1/(2*pi));
        XRNG=2*pi*[-1:0.01:1];
        
        %plot linearized step funs
        LW = [];
        if TOPLOT_LIN_NONLIN == 0 %use nonlinearized
            LW=2;
        elseif TOPLOT_LIN_NONLIN == 1 %plot linearized
            UP_LIN.phase = STEPUP.linPhase;
            UP_LIN.phaseShift = STEPUP.linPhaseShift;
            DOWN_LIN.phase = STEPDOWN.linPhase;
            DOWN_LIN.phaseShift = STEPDOWN.linPhaseShift;
            LW=2;

            for i=1:numel(XRNG)
                Y_UP(i) = -getInVitroPhaseShiftBoot(z*XRNG(i),UP_LIN);
                Y_DOWN(i) = -getInVitroPhaseShiftBoot(z*XRNG(i), DOWN_LIN);
            end
            plot(z*XRNG, Y_UP, 'b-','linewidth',LW);
            hold on;
            plot(z*XRNG, Y_DOWN,'r-','linewidth',LW);

            LW = 0.5;
        end
        
        %double plot interpolated step funs
        sUplt=plot(z*XRNG,-getInVitroPhaseShiftBoot(z*XRNG,STEPUP),...
            'b','linewidth',LW);
        hold on;
        sDplt=plot(z*XRNG,-getInVitroPhaseShiftBoot(z*XRNG,STEPDOWN),'r',...
            'linewidth',LW);
        
        %mark points used in entrained regime
        linDx = []; linLx = [];
        linDy = []; linLy = [];
        cnt = 1;
        for df=1:numel(dutyfrac)
            if entrained(df,b) & dutyfrac(df) > LO_PP/24 & ...
                    dutyfrac(df) < HI_PP/24
                plot(wrapVecAround(duskphase(df,end,b),0,1,'gt'),...
                    -duskphaseshift(df,end,b),'o',...
                    'markerfacecolor',colors(df,:),'markeredgecolor','k',...
                    'linewidth',0.1,'markersize',6);
                hold on;
                plot(wrapVecAround(dawnphase(df,end,b),0.6,1,'gt'),...
                    -dawnphaseshift(df,end,b),'o',...
                    'markerfacecolor',colors(df,:),'markeredgecolor','k',...
                    'linewidth',0.1,'markersize',6);
                
                %collect pts for lin fitting later
                linDx(cnt) = duskphase(df,end,b);
                linDy(cnt) = -duskphaseshift(df,end,b);
                linLx(cnt) = dawnphase(df,end,b);
                linLy(cnt) = -dawnphaseshift(df,end,b);
                cnt = cnt+1;
            end
        end
        
        %linearize L and D locally, in regions used in entrained regime
        loc_d = fitToLine(linDx,linDy);
        loc_l = fitToLine(linLx,linLy);
  
        %title(['boostrap no. ' num2str(b)]);
        xlabel('phase (rad/2\pi)');
        ylabel('phase shift (rad/2\pi)');
        set(gca,'xtick',[-1:0.2:1],'ytick',[-0.4:0.1:0.4],...
            'xlim',[-1 1], 'ylim', [-0.31 0.31]);
        
        grid off;
        legend([sUplt, sDplt],'step up','step down','location','south');
        legend boxoff;
        
        cbar2=colorbar('ytick',[find(colorInd,1,'first'):1:find(colorInd,1,'last')],...
        'yticklabel',24*dutyfrac([find(colorInd,1,'first'):1:find(colorInd,1,'last')]),...
        'ylim',[find(colorInd,1,'first')-0.02 find(colorInd,1,'last')+0.02]);
        title(cbar2,'\tau');
    end
end

set(gcf,'units','inches','position',[0 0 12 3.5]);
if TOEXP_DOUBLEFIG == 1
    export_fig([getDate('yyyy-mm-dd') '_MixMatchNo' num2str(boot) ...
        '_LinBoot_simSlope_LDslope_' getDate() '.pdf'],...
        '-cmyk','-painters',gcf);
end


